version: "3.8"

services:
  bot:
    build: .
    container_name: 1tamilvt-tg
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
